# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07f777c5143020c59e1e3b61ee5c34eb7dc646595c35bf9e734c83809e07c8f37dbf27b2dadbe029f034d4982821888e21b9accb1865421f5fae8994e977d372

test:
  secret_key_base: 1d780c91bc6c9d4fce79a096b4f884eaa672fcec542402e77b493995e72af4b56fccbc5c8edfd54efb43291097ac19189f9aea7f08cd290265d5200a9afea8a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
